# encoding: UTF-8
    
  CREATE TABLE  CUSTOMER (
      ID text,
      ADDR_1 text,
      ADDR_2 text,
      ADDR_3 text,
      CITY text,
      STATE text,
      ZIPCODE text,
      COUNTRY text,
      CONTACT_FIRST_NAME text,
      CONTACT_LAST_NAME text,
      CONTACT_PHONE text,
      CONTACT_FAX text,
      CONTACT_MOBILE text,
      CONTACT_EMAIL text,
      NAME text,
      DISCOUNT_CODE text,
      FREE_ON_BOARD text
  );
    
  CREATE TABLE  EMPLOYEES (
      Frist_Name text NOT NULL,
      Last_Name text NOT NULL,
      Title text,
      Employee_Code text,
      Telephone_Number text,
      Extension text,
      Cellphone_Number text,
      Email_Address text NOT NULL,
      Position integer NOT NULL,
      Description text,
      created_at date,
      updated_at date
  );

  CREATE TABLE EVENT_TYPES (
    HIGHRISE_FIELD TEXT,
    CODE TEXT,
    NAME TEXT,
    PROGRAM_SLUG TEXT,
    POSITION INTEGER,
    CREATED_AT DATE,
    UPDATED_AT DATE
  );
    
  CREATE TABLE EVENTS (
    DATE TEXT,
    SCHOOL_ID INTEGER NOT NULL,
    EVENT_TYPE_ID INTEGER NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE
  );
    
CREATE INDEX INDEX_EVENTS_ON_EVENT_TYPE_ID ON EVENTS (EVENT_TYPE_ID) ;
CREATE INDEX INDEX_EVENTS_ON_SCHOOL_ID ON EVENTS (SCHOOL_ID);
CREATE INDEX INDEX_EVENTS_ON_SCHOOL_ID_AND_EVENT ON EVENTS(SCHOOL_ID, EVENT_TYPE_ID);
    
  CREATE TABLE IMPORTANT_DATE_TYPE_PROGRAMS(
    IMPORTANT_DATE_TYPE_ID INTEGER NOT NULL,
    PROGRAM_SLUG TEXT NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE
  );
    
  CREATE TABLE IMPORTANT_DATE_TYPES (
    HIGHRISE_FIELD TEXT NOT NULL,
    CODE TEXT NOT NULL,
    NAME TEXT,
    DYNAMIC_NAME boolean,
    POSITION INTEGER,
    CREATED_AT DATE,
    UPDATED_AT DATE
  );
    
  CREATE TABLE IMPORTANT_DATES (
    SCHOOL_ID INTEGER NOT NULL,
    IMPORTANT_DATE_TYPE_ID INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    VALUE TEXT NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE
  );
    
  CREATE TABLE JOB_POSTINGS (
    NAME TEXT NOT NULL,
    TITLE TEXT,
    JOB_TYPE_ID INTEGER,
    RESPONSIBILITIES TEXT,
    REQUIRMENTS TEXT,
    EXPIRY_DATE DATE,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    POSITION INTEGER
  );
    
  CREATE TABLE JOB_TYPES (
    NAME TEXT NOT NULL,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    POSITION INTEGER
  );

  CREATE INDEX INDEX_JOB_TYPE_ON_NAME ON JOB_TYPES (NAME);  
  
  CREATE TABLE LOOK_BOOKS (
    CREATED_AT DATE,
    UPDATED_AT DATE,
    SERVICE_ID INTEGER NOT NULL,
    TITLE TEXT,
    PROGRAM_SLUG TEXT
  );

  CREATE TABLE NODES (
    TYPE TEXT NOT NULL,
    OWNER_ID INTEGER NOT NULL,
    OWNER_TYPE TEXT NOT NULL,
    X INTEGER NOT NULL,
    Y INTEGER NOT NULL,
    WIDTH INTEGER NOT NULL,
    HEIGHT INTEGER NOT NULL,
    FONT_FAMILY TEXT,
    POINT_SIZE INTEGER,
    NODE_PHOTO TEXT,
    CROP_X INTEGER,
    CROP_y INTEGER,
    CROP_WIDTH INTEGER,
    CROP_HEIGHT INTEGER,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    NAME TEXT,
    COLOR TEXT DEFAULT '#000000',
    JUNIOR_FIELD TEXT,
    POSITION INTEGER,
    ALIGNMENT TEXT,
    MASK TEXT,
    UPPERCASE BOOLEAN DEFAULT false
  );

  CREATE TABLE PHOTOS (
    FILE_NAME TEXT,
    OWNER_ID INTEGER,
    OWNER_TYPE TEXT,
    DESCRIPTION TEXT,
    POSITION INTEGER,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    TITLE TEXT
  );

    
  CREATE TABLE PHRASES (
    NODE_ID INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    JUNIOR_FIELD TEXT,
    TEXT TEXT,
    PREFIX TEXT,
    SUFFIX TEXT,
    POSITION INTEGER,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
  );

  CREATE INDEX INDEX_PHRASES_ON_NODE_ID ON PHRASES (NODE_ID);     

    
  